### PR TITLE
Remove `SIGUSR2` from `TERMSIGS_DEAULT`

### PR DESCRIPTION
**Pull request by 0x2b3bfa0**
* Fixes https://github.com/celery/celery/issues/2615#issuecomment-314381611

### CODE REVIEW

**Review by auvipy — CHANGES_REQUESTED** [review]
we need to know any side effect of removing this?

**Comment by 0x2b3bfa0** [comment]
@auvipy, I'm not aware of any relevant side effects, but would appreciate another pair of eyes.

**Comment by 0x2b3bfa0** [comment]
@auvipy / @thedrow, ping?

**Comment by 0x2b3bfa0** [comment]
Thank you very much, @auvipy!

**Pull request merged**
