### PR TITLE
upgrade to pytest<6 Fixes #297

### LINKED ISSUE #297: Support pytest 5
Hi,

at least Fedora is moving to pytest 5, billiard requires pytest < 5. 

https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/ZK25O6CXGKPT7IFAE3SX3WSZCK4KBO7S/#ZK25O6CXGKPT7IFAE3SX3WSZCK4KBO7S

It'd be great if pytest 5 could be supported in billiard.

### PR DESCRIPTION
**Pull request by graingert**
pip uses pytest's requires_python to pick the right version for 2.7 and 3+

### CODE REVIEW

**Comment by graingert** [comment]
@mrunge seems to work, test failure is unrelated as it fails on "Python 2.7.13[pypy-7.1.1-final], pytest-4.6.9"

**Comment by graingert** [comment]
I'm running a noop commit to try and prove that the issue is indeed unrelated: https://github.com/celery/billiard/pull/299

**Comment by auvipy** [comment]
pytest 5 do not support python2

**Comment by graingert** [comment]
> pytest 5 do not support python2

please read the description of the PR

**Comment by graingert** [comment]
@auvipy can you re-review?

**Comment by mrunge** [comment]
Thank you for your work on this.

**Pull request merged**
