### PR TITLE
Use `io.open` when opening the file descriptor.

### LINKED ISSUE #149: `os.pipe` returns file descriptors not filenames
Need to fix so that it properly converts file descriptors to file objects.

    Traceback (most recent call last):
      File "/zopt/conda/envs/nanshenv/lib/python2.7/site-packages/billiard/process.py", line 124, in start
        self._popen = self._Popen(self)
      File "/zopt/conda/envs/nanshenv/lib/python2.7/site-packages/billiard/context.py", line 339, in _Popen
        return Popen(process_obj)
      File "/zopt/conda/envs/nanshenv/lib/python2.7/site-packages/billiard/popen_spawn_posix.py", line 38, in __init__
        super(Popen, self).__init__(process_obj)
      File "/zopt/conda/envs/nanshenv/lib/python2.7/site-packages/billiard/popen_fork.py", line 22, in __init__
        self._launch(process_obj)
      File "/zopt/conda/envs/nanshenv/lib/python2.7/site-packages/billiard/popen_spawn_posix.py", line 70, in _launch
        with open(parent_w, 'wb', closefd=False) as f:
    TypeError: coercing to Unicode: need string or buffer, int found

### PR DESCRIPTION
**Pull request by jakirkham**
Fixes #149

### CODE REVIEW

**Comment by jakirkham** [comment]
I should add `open` does not have the keyword argument `closefd`. Only `io.open` has that. Also, `io.open` can open filenames and file descriptors.

**Comment by ask** [comment]
You're right, seems `open` will only support that in Python 3

**Comment by ask** [comment]
Thanks!

**Comment by jakirkham** [comment]
Ah ok, yeah, tricky thing with these backports. Of course.

**Pull request merged**
