### PR TITLE
#296 Add job id to WorkerLostError message

### PR DESCRIPTION
**Pull request by ThomasWunderlich**
Ticket Id: #296 
This adds a job id to the WorkerLostError error message so that it's easier to figure out which job was killed with a worker lost. 

Alternatively, if you don't want to change the exception message I can add this as a separate debug message

### CODE REVIEW

**Comment by ThomasWunderlich** [comment]
@auvipy,
The pypy2 failures are due to the current version of psutil not supporting pypy2. See https://github.com/giampaolo/psutil/issues/1659 
I'll see if I can update tox.ini with the workaround mentioned in the aforementioned link.

**Comment by auvipy** [comment]
can we pin psutils for now?

**Comment by ThomasWunderlich** [comment]
@auvipy Apologies for the delay. I've pinned psutil to the last known good version for pypy2 and added a message to clarify why it's pinned. This should be good to review now

**Comment by auvipy** [comment]
https://github.com/celery/billiard/pull/318

**Pull request merged**
