### PR TITLE
Fix rebuild_ctype losing BufferedWrapper reference on Python 3

### LINKED ISSUE #229: multiple billiard.Value instances sharing the same state
**Problem description**

When using multiple instances of `billiard.Value` and changing one variable's value, the other one is changed as well. In the example below when I update the variable `value`, `done` is set to the same value as well. When replacing `billiard` with `multiprocessing` the example works as expected.

**Example**

See [below](#issuecomment-311695221) for an easier example.

```python
import ctypes
import time
from billiard import Pool, Value


def foo():
    for i in range(10):
        value.value = i
        time.sleep(1)

    done.value = True


def bar():
    while True:
        print(value.value, '\t', done.value)
        time.sleep(0.5)


if __name__ == '__main__':
    value = Value(ctypes.c_int, 0)
    done = Value(ctypes.c_bool, False)

    with Pool() as pool:
        pool.apply_async(bar)
        pool.apply(foo)
```

**Expected output**

```
0 	 False
0 	 False
1 	 False
1 	 False
1 	 False
2 	 False
3 	 False
3 	 False
4 	 False
4 	 False
5 	 False
5 	 False
6 	 False
6 	 False
7 	 False
7 	 False
8 	 False
8 	 False
9 	 False
9 	 False
9 	 True
```

**Actual output**

```
0 	 False
0 	 False
1 	 True
1 	 True
2 	 True
2 	 True
3 	 True
3 	 True
4 	 True
4 	 True
5 	 True
5 	 True
6 	 True
6 	 True
7 	 True
7 	 True
8 	 True
8 	 True
9 	 True
9 	 True
```

**Versions**

```shell
 % pip freeze | grep billiard  
billiard==3.5.0.2
 % python --version          
Python 3.6.0
 % uname -a
Darwin HOST 16.4.0 Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64 x86_64
 % sw_vers -productVersion 
10.12.3
```

### PR DESCRIPTION
**Pull request by Birne94**
Fixes #229 

This is most likely a regression introduced when porting billiard to Python 3 which was for some reason uncovered.

### CODE REVIEW

**Comment by Birne94** [comment]
Python 2.7 tests (cpython und pypy) appear to fail for some unrelated issue, values might be broken on non Python 3.

`OSError: [Errno 17] File exists: '/tmp/pymp-JfdEz9/pym-2339-cp7Vsb'`

**Comment by listingmirror** [comment]
@Birne94 Any idea how this would interact with the "CELERY_WORKER_MAX_MEMORY_PER_CHILD" property? Like are internal properties set with a BufferedWrapper?

I just started using CELERY_WORKER_MAX_MEMORY_PER_CHILD, and I was confused what was going on. I run with 10 subprocesses. When any one of the 10 hit the limit, it seems like all 10 would get killed instead of just the one that used too much memory.  Randomly trying out your branch to see what it does...

**Comment by thedrow** [comment]
The tests fail for Python 2.7 which is a blocker for merging this PR.
The test `test_issue_229` was added in this PR so it means that something is wrong with the current implementation. We could branch on Python 2/3 if needed but this needs to be fixed.

@Birne94 Can you please take a look?

**Comment by Birne94** [comment]
I think the test fails on Python 2.7 because the `billiard.heap.Arena` implementation appears to be buggy, so `billiard.Value` should be unusable from Python 2.7. This issue has been around for some time, but since `billiard.Value` was not tested before it never surfaced.

AppVeyor builds fail on master with the same errors, so they are unrelated.

I can have a look at it tomorrow and see if I can fix it. Not sure though if this is still in the scope of this PR.

**Comment by thedrow** [comment]
We'll have to extend the scope of the PR if that's the case.
I don't mind releasing 3.5.0.4 if you provide these fixes.

**Comment by Birne94** [comment]
I have added a fix for python2.7 and the tests for values from the cpython multiprocessing library. It appears to be working now.

**Comment by thedrow** [comment]
Thanks!

**Pull request merged**
