### PR TITLE
Add support for Python 3.11 _posixsubprocess.fork_exec() arguments

### PR DESCRIPTION
**Pull request by hroncok**

### CODE REVIEW

**Review by auvipy — CHANGES_REQUESTED** [review]
possible to add some tests as well?

**Comment by hroncok** [comment]
The tests failed without this. And if you mean CI for 3.11, I'd prefer if you do that. We are handling hundreds of similar issues in Fedora now and I unfortunately cannot fine tune every upstream hot fix. Sorry about that.

**Comment by auvipy** [comment]
ok

**Comment by auvipy** [comment]
thank you

**Pull request merged**
