### PR TITLE
fix test_spawn on pypy

### PR DESCRIPTION
**Pull request by graingert**
use sigusr1 for pdeathsignal test

### CODE REVIEW

**Comment by auvipy** [comment]
should we merge this?

**Comment by graingert** [comment]
Bear in mind this is due to a pypy bug that's now fixed

**Comment by graingert** [comment]
https://github.com/giampaolo/psutil/issues/1659 but I think using a Queue and signal handler is nicer anyway

**Comment by auvipy** [comment]
@thedrow

**Pull request merged**
