### PR TITLE
Logging max memory reached at INFO rather than WARNING (#255)

### PR DESCRIPTION
**Pull request by truthdoug**

### CODE REVIEW

**Comment by thedrow** [comment]
Why do we want to change this?

**Comment by truthdoug** [comment]
As I understand this code, what's happening here is that it's checking to see if the process has reached its maximum memory, as configured earlier. If it has reached that, the pool should be recycled.  Since this is expected functionality, it is not an error condition and should not be logged as such.

The practical impact for my team is that we have alerts on various logs which notify us via email when there are log messages logged at ERRROR severity.

@auvipy I'll reexamine this code and see about adding a test for this. Thanks.

**Comment by thedrow** [comment]
At the very least this should be a warning.
While this is normal behavior, users should be notified about it.
Setting memory limits is done to avoid crashing the server. Users should be alerted in that case.
If this log was emitted as info, it would go unnoticed.

**Comment by truthdoug** [comment]
I've updated to log at WARNING. I cannot look at adding tests at this moment. There are not currently any tests relating to max memory or logging.

**Pull request merged**
